### ISSUE TITLE
JSX fragments adds "undefined" text label

### ISSUE THREAD

**Issue by Oery** [Aylur/astal#106]
**Describe the bug**
Rendering a fragment using `<></>` cause a new label to be appended. It displays `undefined`.

**To Reproduce**

```jsx
// The code that should work:

function FragmentWithChildren() {
    return (
        <>
            <label label='Text1' />
            <label label='Text2' />
        </> 
    );
}

// What is rendered:

function FragmentWithChildren() {
    return (
        <>
            <label label='Text1' />
            <label label='Text2' />
            <label label='undefined' />
        </> 
    );
}

```
**Expected behavior**
JSX Fragment should not render another label.

**Additional context**
Styling `label` in scss affects the `undefined`.

**Comment by Aylur** [comment]
Fragments are purposefully undocumented, because its just an experimental thing currently.
All it does is basically handle if there are any bindings as a child and return a flattened array that container widgets like `box` can handle. Which means its type is also a lie, it does not return a `JSX.Element` aka `Gtk.Widget` but either `Array<Gtk.Widget>` or `Binding<Array<Gtk.Widget>>`. Its rendering will depend on what type of container you pass it to, which I'm assuming you used a `centerbox` which why it rendered undefined.

```jsx
function FragmentWithChildren() {
    return (
        <>
            <label label='Text1' />
            <label label='Text2' />
            <box /> // placeholder
        </> 
    );
}

<centerbox>
  <FragmentWithChildren />
</centerbox>
```

But again, this is experimental and this behavior might change in the future, you should use a `box` instead of a fragment for now.

**Comment by Oery** [comment]
I was using a regular Box. When using centerbox I directly get a wrong type error.
My use case is conditionally rendering 2 elements in a box, but I want the box to be there even if the condition is false. Without fragment I would need to put a box in my box, which is what I've done atm.

My original code:
```jsx
import { bind } from 'astal';
import { Gtk } from 'astal/gtk3';
import Hyprland from 'gi://AstalHyprland';

export default function FocusedClient() {
    const hypr = Hyprland.get_default();
    const focused = bind(hypr, 'focusedClient');

    return (
        <box className='focused_app' vertical visible={focused.as(Boolean)} valign={Gtk.Align.CENTER}>
            {focused.as(
                (client) =>
                    client && (
                        <>
                            <label
                                className='class'
                                halign={Gtk.Align.START}
                                label={bind(client, 'class').as(String)}
                            />
                            <label
                                className='title'
                                halign={Gtk.Align.START}
                                label={bind(client, 'title').as(String)}
                            />
                        </>
                    )
            )}
        </box>
    );
}
```
