### ISSUE TITLE
Untie Inhibit Manager from Window 

### ISSUE THREAD

**Issue by craiggwilson** [Aylur/astal#161]
I tried AGS a while ago and was missing the inhibit manager (tried building one, etc...). BTW: I love this project and you've done a great job with it!

I found that this is implemented, but tied directly to an Astal.Window. Is there a reason for this as opposed to offering it as a "service"? I have a button on my bar that toggles this on or off, but I have 3 bars for 3 monitors which all have their own windows. It feels like a window isn't the right place to hang this off of.

Perhaps I'll try to move it (or offer it also elsewhere) and put up a PR, but am wondering what the reason is for putting at this level and if I'm missing something.

**Comment by kotontrion** [comment]
It uses the idle inhibit wayland protocol. An inhibitor is attached to a wl_surface, which is associated with a window. This allows more fine granular control, like eg theoretically the compositor could turn off other monitors but not the one which displays the window with the inhibitor, not sire something like this is actually done by any compositor though. 

So the idle inhibitors are tied to windows by design in wayland.

**Comment by craiggwilson** [comment]
Ok, fair enough and thanks for the explanation. I worked around this by toggling a global variable that then toggles the inhibit on each monitor's bar simultaneously. Seems to work. 

I appreciate the feature. :)
