### ISSUE TITLE
Hyprland.message_async fails when only one input parameter given

### ISSUE THREAD

**Issue by FjedorGaede** [Aylur/astal#96]
**Describe the bug**
When using the `Hyprland.message_async` - e.g. to dispatch workspace switches, the type in typescript suggests that you can only pass one string argument to the function. But when I for example run `hyprland.message_async("dispatch workspace 1")` it will fail with the following error:
```
(gjs:84853): Gjs-CRITICAL **: 21:21:18.942: JS ERROR: TypeError: method AstalHyprland.Hyprland.message_async: At least 2 arguments required, but only 1 passed
dispatch@file:///run/user/1000/ags.js:958:31
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
``` 

When using `hyprland.message_async("dispatch workspace 1", () => {})` it works as expected.

**To Reproduce**
I have this `JSX.Element` that can be used to reproduce the issue: 
```tsx:hyprtest.tsx
import Hyprland from "gi://AstalHyprland";

const hyprland = Hyprland.get_default();

const dispatch_broken = () =>
  hyprland.message_async(`dispatch exec notify-send "test"`);

const dispatch_working = () =>
  hyprland.message_async(`dispatch exec notify-send "test"`, () => {});

export const HyprTest = () => (
  <box>
    <button onClick={dispatch_broken} label="broken" />
    <button onClick={dispatch_working} label="working" />
  </box>
);

```

**Comment by Aylur** [comment]
This is because gio async functions are not yet automatically converted into js functions that return promises, but the types are.
You can pass `null` as the callback or use [Gio._promisify](https://gjs.guide/guides/gjs/asynchronous-programming.html#promisify-helper).
This will be automatically done in some future version of gjs as the [notations in gir for gio asnyc](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3746) functions have been merged.
